//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input Actions/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""ebfcd3db-0970-4083-b0f2-0bc329c727d2"",
            ""actions"": [
                {
                    ""name"": ""PitchRoll"",
                    ""type"": ""Value"",
                    ""id"": ""b7edcbee-169d-4589-bfd3-832ca994e399"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LiftYaw"",
                    ""type"": ""Value"",
                    ""id"": ""9824ae96-aa0c-4b3f-8a0d-f34bc29a8aa2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CamRotation"",
                    ""type"": ""Value"",
                    ""id"": ""9e196388-e840-48fb-9b57-2992bdae0f30"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""19d3464d-7c2c-40a5-b693-6c3419242ae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleMotor"",
                    ""type"": ""Button"",
                    ""id"": ""bc595d69-21eb-487a-9b9b-901495eac7f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeMode"",
                    ""type"": ""Button"",
                    ""id"": ""441be819-a1ff-427a-a66e-6c3048035c06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleHover"",
                    ""type"": ""Button"",
                    ""id"": ""33939383-8ace-4b9d-bf05-da4c6c745f73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchCamera"",
                    ""type"": ""Button"",
                    ""id"": ""5c14c41d-e8bb-4aa4-a109-e8595befa94d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""Value"",
                    ""id"": ""c672761b-9c39-4674-81b6-fff995aebd7c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""ee6ac279-f27c-4d22-a299-c6310af90798"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Main Action"",
                    ""type"": ""Button"",
                    ""id"": ""e17830b9-2978-4053-a14d-41bd87ec3fc9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Secondary Action"",
                    ""type"": ""Button"",
                    ""id"": ""e7c457a2-005d-4d8c-9185-887748d72b95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldToCheats"",
                    ""type"": ""Button"",
                    ""id"": ""d739f884-fcfc-4c47-ac73-6677de25c4a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7278c182-4253-4e28-ac8b-35ca5ef4575e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad Arrows"",
                    ""id"": ""c9c272be-227b-49e8-804c-ba7836870c40"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b92493c6-4449-4709-80dd-7955656c9904"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f91b35b5-37fb-4591-b924-d9ac1f3bd713"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d0873e7d-e93e-4ec2-bce4-7796a9246fbc"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6a1eb2fa-c89a-4674-84cf-c3696fb644db"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1dbef0b4-0fb7-45c3-a40e-99da5ff8b185"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0586cc3-8ebd-413f-bf59-6031f30e261a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdbbe5a6-23dd-46a6-ad19-c1de5211361f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMotor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77824b0e-6f66-441c-80ad-4fc599655e56"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleMotor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""D-pad Left/Right"",
                    ""id"": ""f8178c6b-2959-4383-9e3e-ec664c3d5dd7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8aa625b6-949d-4524-8992-cfb2ac3d386b"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""79fcd114-90b9-4ccf-b191-f4cd258e10dd"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard Arrows Left/Right"",
                    ""id"": ""b12223cf-8f86-489e-8676-f5b7b5220bfc"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMode"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b666154c-a1ed-4c85-96a9-bd6f977c512f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f0d85aa4-f3d5-4b40-bf7f-c15a5bcdba88"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0f49344c-893e-451d-af0a-2941c9341b8e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleHover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06525d06-b730-48c3-abc2-6c5937faca7b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleHover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""966a8210-2c27-469b-8263-5aa136adc906"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88b0eb07-1c0b-4925-b384-24290236631a"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d289169-d927-4aeb-a1a7-dd439753be4b"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cefe9a4-c3ba-40ed-93bd-eb4e878587c8"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85b050e4-e394-4bf0-b370-90c04e2467f9"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""46b32cf4-5366-4b8d-86e6-0b60eed39bb8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fb6928b-c4bf-49d4-8fdf-01c5a7dc3fc3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Main Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a74ff93f-d41a-4f9d-8ba8-3d6bd04d1f71"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Main Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad2528f1-b42c-4a56-9f61-e90d79e50d25"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Secondary Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6716a20-7ecb-4841-93c5-49f7a92a1661"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Secondary Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""01bae36c-94f6-43a7-95f3-2cad86574abb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e1326a1f-b88b-46b9-ad98-281486f4e0b9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cfbd722b-8f64-4079-815c-639f3fb8d1aa"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""24c55280-134d-4eb8-9fdf-979b1e4834be"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""367f6e6a-a69c-4c87-a452-63b40e45d8ac"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5c409348-c95e-4a8a-bf3f-22d977a1a8eb"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e0e168e8-ba85-445b-a740-6114d902dfeb"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""LiftYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keys SpaceShift QE"",
                    ""id"": ""6f48ed7c-614f-4cc6-a5a5-b9317bf3323a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftYaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2b5d512e-ad23-4bd3-b795-38c8c95577dd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""60b1dcbe-d71e-421f-85e9-45457424cd45"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4f3e1856-cbf7-4118-a0a2-43aa26b72899"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""69170b0a-dc74-4f9f-a44e-28b3ee5b699d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LiftYaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""598bcf6e-3526-4849-b5ef-c27c76ee1d20"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldToCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0c3eecc-4c78-4592-abfb-ba455381a3da"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldToCheats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_PitchRoll = m_Gameplay.FindAction("PitchRoll", throwIfNotFound: true);
        m_Gameplay_LiftYaw = m_Gameplay.FindAction("LiftYaw", throwIfNotFound: true);
        m_Gameplay_CamRotation = m_Gameplay.FindAction("CamRotation", throwIfNotFound: true);
        m_Gameplay_Reset = m_Gameplay.FindAction("Reset", throwIfNotFound: true);
        m_Gameplay_ToggleMotor = m_Gameplay.FindAction("ToggleMotor", throwIfNotFound: true);
        m_Gameplay_ChangeMode = m_Gameplay.FindAction("ChangeMode", throwIfNotFound: true);
        m_Gameplay_ToggleHover = m_Gameplay.FindAction("ToggleHover", throwIfNotFound: true);
        m_Gameplay_SwitchCamera = m_Gameplay.FindAction("SwitchCamera", throwIfNotFound: true);
        m_Gameplay_Point = m_Gameplay.FindAction("Point", throwIfNotFound: true);
        m_Gameplay_Pause = m_Gameplay.FindAction("Pause", throwIfNotFound: true);
        m_Gameplay_MainAction = m_Gameplay.FindAction("Main Action", throwIfNotFound: true);
        m_Gameplay_SecondaryAction = m_Gameplay.FindAction("Secondary Action", throwIfNotFound: true);
        m_Gameplay_HoldToCheats = m_Gameplay.FindAction("HoldToCheats", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_PitchRoll;
    private readonly InputAction m_Gameplay_LiftYaw;
    private readonly InputAction m_Gameplay_CamRotation;
    private readonly InputAction m_Gameplay_Reset;
    private readonly InputAction m_Gameplay_ToggleMotor;
    private readonly InputAction m_Gameplay_ChangeMode;
    private readonly InputAction m_Gameplay_ToggleHover;
    private readonly InputAction m_Gameplay_SwitchCamera;
    private readonly InputAction m_Gameplay_Point;
    private readonly InputAction m_Gameplay_Pause;
    private readonly InputAction m_Gameplay_MainAction;
    private readonly InputAction m_Gameplay_SecondaryAction;
    private readonly InputAction m_Gameplay_HoldToCheats;
    public struct GameplayActions
    {
        private @PlayerAction m_Wrapper;
        public GameplayActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @PitchRoll => m_Wrapper.m_Gameplay_PitchRoll;
        public InputAction @LiftYaw => m_Wrapper.m_Gameplay_LiftYaw;
        public InputAction @CamRotation => m_Wrapper.m_Gameplay_CamRotation;
        public InputAction @Reset => m_Wrapper.m_Gameplay_Reset;
        public InputAction @ToggleMotor => m_Wrapper.m_Gameplay_ToggleMotor;
        public InputAction @ChangeMode => m_Wrapper.m_Gameplay_ChangeMode;
        public InputAction @ToggleHover => m_Wrapper.m_Gameplay_ToggleHover;
        public InputAction @SwitchCamera => m_Wrapper.m_Gameplay_SwitchCamera;
        public InputAction @Point => m_Wrapper.m_Gameplay_Point;
        public InputAction @Pause => m_Wrapper.m_Gameplay_Pause;
        public InputAction @MainAction => m_Wrapper.m_Gameplay_MainAction;
        public InputAction @SecondaryAction => m_Wrapper.m_Gameplay_SecondaryAction;
        public InputAction @HoldToCheats => m_Wrapper.m_Gameplay_HoldToCheats;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @PitchRoll.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPitchRoll;
                @PitchRoll.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPitchRoll;
                @PitchRoll.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPitchRoll;
                @LiftYaw.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftYaw;
                @LiftYaw.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftYaw;
                @LiftYaw.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnLiftYaw;
                @CamRotation.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCamRotation;
                @CamRotation.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCamRotation;
                @CamRotation.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnCamRotation;
                @Reset.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReset;
                @Reset.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReset;
                @Reset.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnReset;
                @ToggleMotor.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnToggleMotor;
                @ToggleMotor.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnToggleMotor;
                @ToggleMotor.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnToggleMotor;
                @ChangeMode.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeMode;
                @ChangeMode.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeMode;
                @ChangeMode.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeMode;
                @ToggleHover.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnToggleHover;
                @ToggleHover.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnToggleHover;
                @ToggleHover.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnToggleHover;
                @SwitchCamera.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCamera;
                @SwitchCamera.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCamera;
                @SwitchCamera.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchCamera;
                @Point.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPoint;
                @Pause.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnPause;
                @MainAction.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMainAction;
                @MainAction.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMainAction;
                @MainAction.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMainAction;
                @SecondaryAction.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryAction;
                @SecondaryAction.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSecondaryAction;
                @HoldToCheats.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHoldToCheats;
                @HoldToCheats.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHoldToCheats;
                @HoldToCheats.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnHoldToCheats;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PitchRoll.started += instance.OnPitchRoll;
                @PitchRoll.performed += instance.OnPitchRoll;
                @PitchRoll.canceled += instance.OnPitchRoll;
                @LiftYaw.started += instance.OnLiftYaw;
                @LiftYaw.performed += instance.OnLiftYaw;
                @LiftYaw.canceled += instance.OnLiftYaw;
                @CamRotation.started += instance.OnCamRotation;
                @CamRotation.performed += instance.OnCamRotation;
                @CamRotation.canceled += instance.OnCamRotation;
                @Reset.started += instance.OnReset;
                @Reset.performed += instance.OnReset;
                @Reset.canceled += instance.OnReset;
                @ToggleMotor.started += instance.OnToggleMotor;
                @ToggleMotor.performed += instance.OnToggleMotor;
                @ToggleMotor.canceled += instance.OnToggleMotor;
                @ChangeMode.started += instance.OnChangeMode;
                @ChangeMode.performed += instance.OnChangeMode;
                @ChangeMode.canceled += instance.OnChangeMode;
                @ToggleHover.started += instance.OnToggleHover;
                @ToggleHover.performed += instance.OnToggleHover;
                @ToggleHover.canceled += instance.OnToggleHover;
                @SwitchCamera.started += instance.OnSwitchCamera;
                @SwitchCamera.performed += instance.OnSwitchCamera;
                @SwitchCamera.canceled += instance.OnSwitchCamera;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @MainAction.started += instance.OnMainAction;
                @MainAction.performed += instance.OnMainAction;
                @MainAction.canceled += instance.OnMainAction;
                @SecondaryAction.started += instance.OnSecondaryAction;
                @SecondaryAction.performed += instance.OnSecondaryAction;
                @SecondaryAction.canceled += instance.OnSecondaryAction;
                @HoldToCheats.started += instance.OnHoldToCheats;
                @HoldToCheats.performed += instance.OnHoldToCheats;
                @HoldToCheats.canceled += instance.OnHoldToCheats;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnPitchRoll(InputAction.CallbackContext context);
        void OnLiftYaw(InputAction.CallbackContext context);
        void OnCamRotation(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnToggleMotor(InputAction.CallbackContext context);
        void OnChangeMode(InputAction.CallbackContext context);
        void OnToggleHover(InputAction.CallbackContext context);
        void OnSwitchCamera(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnMainAction(InputAction.CallbackContext context);
        void OnSecondaryAction(InputAction.CallbackContext context);
        void OnHoldToCheats(InputAction.CallbackContext context);
    }
}
